apiVersion: v1
kind: Service
metadata:
  name: twitter-api-stg
spec:
  selector:
    name: twitter-api-stg
  ports:
  - port: 10085
    targetPort: 8002
    nodePort: 30087
    protocol: TCP
    name: api-http
  externalIPs:
  - 192.168.0.21
  - 192.168.0.22
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: twitter-api-stg
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: twitter-api-stg
    spec:
      hostname: api-server
      containers:
      - name: mysql-server
        image: mysql:5.7
        env: 
        - name: MYSQL_DATABASE
          value: django
        - name: MYSQL_USER
          value: apiadmin
        - name: MYSQL_PASSWORD
          value: apiadmin_pwd
        - name: MYSQL_ROOT_PASSWORD
          value: root_pwd
        args:
        - --character-set-server=utf8mb4
        - --collation-server=utf8mb4_unicode_ci
        ports:
        - containerPort: 3306
          name: api-mysql
        volumeMounts:
        - name: twi-db-stg-pv
          mountPath: /var/lib/mysql
      - name: api-server
        image: pshost02:5000/study/django:1.1
        ports:
        - containerPort: 8002
          name: django-server
        volumeMounts:
        - name: twi-ap-stg-pv
          mountPath: /opt
      volumes:
        - name: twi-db-stg-pv
          persistentVolumeClaim:
            claimName: twi-db-stg-claim
        - name: twi-ap-stg-pv
          persistentVolumeClaim:
            claimName: twi-ap-stg-claim
