apiVersion: v1
kind: Service
metadata:
  name: mariadb-svc
spec:
  selector:
    app: redmine
  ports:
  - port: 80
    targetPort: 3306
    nodePort: 30002
    protocol: TCP
  externalIPs:
  - 192.168.0.21
  - 192.168.0.22
  type: NodePort
