apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redmine-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redmine
    spec:
      containers:
      - image: myredmine
        name: redmine-app
        ports:
        - containerPort: 80
          name: redmine-app
