apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: log-server-dp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: log-server
    spec:
      hostname: log-server
      containers:
      - name: mysql-server
        image: mysql:5.7
        env: 
        - name: MYSQL_USERMYSQL_DATABASE
          value: log-server
        - name: MYSQL_USER
          value: logadmin
        - name: MYSQL_PASSWORD
          value: logadmin_pwd
        - name: MYSQL_ROOT_PASSWORD
          value: root_pwd
        args:
        - --character-set-server=utf8mb4
        - --collation-server=utf8mb4_unicode_ci
        ports:
        - containerPort: 3306
          name: log-mysql
        volumeMounts:
        - name: log-mysql-pv
          mountPath: /var/lib/mysql
      volumes:
        - name: log-mysql-pv
          persistentVolumeClaim:
            claimName: pv005-claim

