apiVersion: v1
kind: Service
metadata:
  name: redmine-svc
spec:
  selector:
    name: redmine
  ports:
  - port: 10080
    targetPort: 3000
    nodePort: 30080
    protocol: TCP
    name: redmine-http
  externalIPs:
  - 192.168.0.21
  - 192.168.0.22
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redmine-dp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: redmine
    spec:
      containers:
      - image: redmine
        name: redmine-ap
        ports:
        - containerPort: 3000
          name: redmine-http
        volumeMounts:
        - name: redmine-pv
          mountPath: /usr/src/redmine
      imagePullSecrets:
      - name: regcred
      volumes:
        - name: redmine-pv
          persistentVolumeClaim:
            claimName: pv003-claim


