apiVersion: v1
kind: Service
metadata:
  name: zabbix-svc
spec:
  selector:
    app: zabbix
  ports:
  - port: 10081
    targetPort: 80
    nodePort: 30081
    protocol: TCP
    name: zabbix-http
  - port: 10082
    targetPort: 10051
    nodePort: 30082
    protocol: TCP
    name: zabbix-server
  externalIPs:
  - 192.168.0.21
  - 192.168.0.22
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zabbix-dp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: zabbix
    spec:
      hostname: zabbix-server
      containers:
      - name: mysql-server
        image: mysql:5.7
        env: 
        - name: MYSQL_DATABASE
          value: zabbix
        - name: MYSQL_USER
          value: zabbix
        - name: MYSQL_PASSWORD
          value: zabbix_pwd
        - name: MYSQL_ROOT_PASSWORD
          value: root_pwd
        args:
        - --character-set-server=utf8mb4
        - --collation-server=utf8mb4_unicode_ci
        ports:
        - containerPort: 3306
          name: zabbix-mysql
        volumeMounts:
        - name: zabbix-mysql-pv
          mountPath: /var/lib/mysql
      - name: mysql-jg
        image: zabbix/zabbix-java-gateway:centos-3.4-latest
        ports:
        - containerPort: 10052
          name: mysql-jg
      - name: zabbix-server
        image: zabbix/zabbix-server-mysql:centos-3.4-latest
        env: 
        - name: DB_SERVER_HOST
          value: zabbix-server
        - name: MYSQL_DATABASE
          value: zabbix
        - name: MYSQL_USER
          value: zabbix
        - name: MYSQL_PASSWORD
          value: zabbix_pwd
        - name: MYSQL_ROOT_PASSWORD
          value: root_pwd
        - name: ZBX_JAVAGATEWAY
          value: zabbix-server
        ports:
        - containerPort: 10051
          name: zabbix-server
      - name: zabbix-web
        image: zabbix/zabbix-web-nginx-mysql:centos-3.4-latest
        env: 
        - name: DB_SERVER_HOST
          value: zabbix-server
        - name: MYSQL_DATABASE
          value: zabbix
        - name: MYSQL_USER
          value: zabbix
        - name: MYSQL_PASSWORD
          value: zabbix_pwd
        - name: MYSQL_ROOT_PASSWORD
          value: root_pwd
        ports:
        - containerPort: 80
          name: zabbix-web
      volumes:
        - name: zabbix-mysql-pv
          persistentVolumeClaim:
            claimName: pv004-claim
