apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: python-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: python-app
    spec:
      containers:
      - image: 192.168.0.21:5000/study/python-app
        name: python-app
        ports:
        - containerPort: 8000
          name: django-api
      imagePullSecrets:
      - name: regcred
        