apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: python-app
spec:
  concurrencyPolicy: Replace
  schedule: "*/10 9-15 * * *"
  replicas: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            name: python-app
        spec:
          containers:
          - image: 192.168.0.21:5000/study/python-app:0.4
            args:
            - "/usr/local/pyenv/shims/python"
            - "/root/myproject/investmentTools/getBlandInfo.py"
            name: python-app
            ports:
            - containerPort: 8000
              name: django-api
          imagePullSecrets:
          - name: regcred
          nodeName: kube-node1
