apiVersion: v1
kind: Service
metadata:
  name: django-svc
spec:
  selector:
    name: python-app
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30005
    protocol: TCP
  externalIPs:
  - 192.168.0.21
  - 192.168.0.22
  type: NodePort
