apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/created-by: |
      {"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicaSet","namespace":"default","name":"rails-app-601935175","uid":"445d0808-bd6f-11e8-9bfe-00155d0b030c","apiVersion":"extensions","resourceVersion":"4149968"}}
  creationTimestamp: 2018-11-18T06:33:47Z
  generateName: rails-app-601935175-
  labels:
    app: rails-app
    pod-template-hash: "601935175"
  name: rails-app-601935175-pg4gw
  namespace: default
  ownerReferences:
  - apiVersion: extensions/v1beta1
    controller: true
    kind: ReplicaSet
    name: rails-app-601935175
    uid: 445d0808-bd6f-11e8-9bfe-00155d0b030c
  resourceVersion: "4173520"
  selfLink: /api/v1/namespaces/default/pods/rails-app-601935175-pg4gw
  uid: e789bf65-eafb-11e8-9bfe-00155d0b030c
spec:
  containers:
  - image: 192.168.0.21:5000/study/rails:1.0
    imagePullPolicy: IfNotPresent
    name: rails-app
    ports:
    - containerPort: 3000
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-dclpn
      readOnly: true
  dnsPolicy: ClusterFirst
  imagePullSecrets:
  - name: regcred
  nodeName: kube-node2
  restartPolicy: Always
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  volumes:
  - name: default-token-dclpn
    secret:
      defaultMode: 420
      secretName: default-token-dclpn
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: 2018-11-18T06:33:48Z
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: 2018-11-23T15:36:58Z
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: 2018-11-18T06:33:47Z
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://9bcf4f822740eb08baef6ff94d06262e1357dcca77e5dd7290de30d15429ae09
    image: 192.168.0.21:5000/study/rails:1.0
    imageID: docker-pullable://192.168.0.21:5000/study/rails@sha256:ea23eba51623a1438a6096161b09eec6de8f907f455dacf5456e8fd1fb1bd335
    lastState:
      terminated:
        containerID: docker://e46901d1a343bc39dcf6140303d5c145d0d430a77b02ed59c1c87fa2a6d59b07
        exitCode: 137
        finishedAt: 2018-11-23T15:36:45Z
        reason: Error
        startedAt: 2018-11-18T06:33:58Z
    name: rails-app
    ready: true
    restartCount: 1
    state:
      running:
        startedAt: 2018-11-23T15:36:58Z
  hostIP: 192.168.0.22
  phase: Running
  podIP: 172.30.20.3
  startTime: 2018-11-18T06:33:48Z
