apiVersion: v1
kind: Service
metadata:
  name: rails-app
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30006
    protocol: TCP
  externalIPs:
  - 192.168.0.21
  - 192.168.0.22
  selector:
    app: rails-app
