apiVersion: v1
kind: Service
metadata:
  name: jenkins-svc
spec:
  selector:
    app: web
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30001
    protocol: TCP
  externalIPs:
  - 192.168.0.21
  - 192.168.0.22
  type: NodePort  
