apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: petshop
    spec:
      containers:
      - name: container1
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30000
    protocol: TCP
  selector:
    app: petshop
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dev-ingress
spec:
  backend:
    serviceName: nginx
    servicePort: 80
